In [ ]:
import pandas as pd

car_sales = pd.read_csv("car-sales.csv")
car_sales_missing = pd.read_csv("car-sales-missing-data.csv")

In [ ]:
car_sales

In [ ]:
car_sales_missing

In [ ]:
car_sales_missing = car_sales_missing.dropna()

In [ ]:
car_sales_missing

In [ ]:
car_sales_missing.to_csv("car_sales_missing_dropped.csv")

In [14]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [17]:
seats = pd.DataFrame([5, 5, 5, 5, 5, 5])

In [18]:
car_sales["Seats"] = seats

In [19]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  Toyota  White         150043      4   $4,000.00    5.0
1   Honda    Red          87899      4   $5,000.00    5.0
2  Toyota   Blue          32549      3   $7,000.00    5.0
3     BMW  Black          11179      5  $22,000.00    5.0
4  Nissan  White         213095      4   $3,500.00    5.0
5  Toyota  Green          99213      4   $4,500.00    5.0
6   Honda   Blue          45698      4   $7,500.00    NaN
7   Honda   Blue          54738      4   $7,000.00    NaN
8  Toyota  White          60000      4   $6,250.00    NaN
9  Nissan  White          31600      4   $9,700.00    NaN

In [22]:
car_sales.fillna(5, inplace=True)

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  Toyota  White         150043      4   $4,000.00    5.0
1   Honda    Red          87899      4   $5,000.00    5.0
2  Toyota   Blue          32549      3   $7,000.00    5.0
3     BMW  Black          11179      5  $22,000.00    5.0
4  Nissan  White         213095      4   $3,500.00    5.0
5  Toyota  Green          99213      4   $4,500.00    5.0
6   Honda   Blue          45698      4   $7,500.00    5.0
7   Honda   Blue          54738      4   $7,000.00    5.0
8  Toyota  White          60000      4   $6,250.00    5.0
9  Nissan  White          31600      4   $9,700.00    5.0

In [23]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  Toyota  White         150043      4   $4,000.00    5.0
1   Honda    Red          87899      4   $5,000.00    5.0
2  Toyota   Blue          32549      3   $7,000.00    5.0
3     BMW  Black          11179      5  $22,000.00    5.0
4  Nissan  White         213095      4   $3,500.00    5.0
5  Toyota  Green          99213      4   $4,500.00    5.0
6   Honda   Blue          45698      4   $7,500.00    5.0
7   Honda   Blue          54738      4   $7,000.00    5.0
8  Toyota  White          60000      4   $6,250.00    5.0
9  Nissan  White          31600      4   $9,700.00    5.0

In [24]:
car_sales["No of wheels"] = 4

In [25]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats  No of wheels
0  Toyota  White         150043      4   $4,000.00    5.0             4
1   Honda    Red          87899      4   $5,000.00    5.0             4
2  Toyota   Blue          32549      3   $7,000.00    5.0             4
3     BMW  Black          11179      5  $22,000.00    5.0             4
4  Nissan  White         213095      4   $3,500.00    5.0             4
5  Toyota  Green          99213      4   $4,500.00    5.0             4
6   Honda   Blue          45698      4   $7,500.00    5.0             4
7   Honda   Blue          54738      4   $7,000.00    5.0             4
8  Toyota  White          60000      4   $6,250.00    5.0             4
9  Nissan  White          31600      4   $9,700.00    5.0             4